import type { SeoPage } from './seoPages'

// Shared shell, separately authored intent and working tool configuration.
const base = {
  social: false,
  defaults: { workDuration: 25, shortBreak: 5, longBreak: 15, longBreakAfter: 4 },
  socialHeading: 'Work alongside others',
  socialCopy: 'Open the shared workspace when you want live company.',
  audienceHeading: 'Make room for your next session',
  advantageHeading: 'Continue in Pomo Cowork',
  advantage: 'The main workspace connects focus sessions with tasks and live coworkers. Sign in for saved history and project features, or start with a guest timer.',
} satisfies Partial<SeoPage>

export const intentSeoPages = {
  'aesthetic-pomodoro-timer': {
    ...base,
    keyword: 'Aesthetic Pomodoro timer',
    secondaryKeywords: ['pretty pomodoro timer', 'beautiful pomodoro timer'],
    title: 'Aesthetic Pomodoro Timer — Calm Focus & Breaks | Pomo Cowork',
    description: 'A beautiful Pomodoro timer with a quiet landscape, ambient sounds and fullscreen. Start a 25/5 cycle, adjust your breaks and focus on one task.',
    heading: 'Aesthetic Pomodoro timer, with space to breathe',
    intro: 'A pretty Pomodoro timer can still be practical. A calm landscape frames your focus block, break controls stay close, and ambient sounds are ready when you want them.',
    cta: 'Set up your Pomodoro',
    appearance: 'aesthetic',
    experience: 'aesthetic',
    timerNote: '25 minutes of focus, five minutes of rest, and a 15-minute long break after four rounds. Fullscreen keeps the guide out of view.',
    explanationHeading: 'A beautiful timer with a work-and-break rhythm',
    explanation: [
      'An aesthetic Pomodoro timer combines the visual atmosphere of a desk clock with a repeatable work-and-break cycle. Choose one activity before you start: outline an essay, revise a topic, or work through a chapter. The default 25-minute block is a commitment to that activity, not a deadline to finish everything.',
      'The landscape stays still behind the timer. Open the ambient mixer to layer rain, wind, or a fireplace, then adjust the shared volume. Audio starts when you choose a sound; opening the page does not begin playback. Fullscreen enlarges the working area and leaves this guide outside it.',
      'When a focus block ends, use the break controls to step away. Automatic transitions follow your timer settings. You can change durations in settings if your task needs a different rhythm, and an existing active or paused session retains its timing.',
    ],
    stepsHeading: 'Build a small study ritual',
    steps: ['Choose the task for your next 25 minutes.', 'Pick an ambient sound and a comfortable volume, or leave the room quiet.', 'Enter Fullscreen and press Start when your materials are ready.', 'Use a short break between rounds and a longer break after four.'],
    benefits: [
      { title: 'A still landscape', text: 'The background gives the timer a place on your desk without a moving scene competing with your notes.' },
      { title: 'Sound within reach', text: 'Mix the existing ambient tracks without leaving your focus page.' },
      { title: 'Breaks remain visible', text: 'Work, short break, and long break keep the Pomodoro structure easy to follow.' },
    ],
    audience: [
      { title: 'Study desks', text: 'Keep a calm timer beside a textbook or revision notes.' },
      { title: 'Creative sessions', text: 'Give sketching, outlining, or editing a distinct beginning and end.' },
    ],
    faq: [
      { question: 'Is this a pretty Pomodoro timer or just a clock?', answer: 'It is a working Pomodoro countdown with work and break modes. For the current time of day with animated digits, open the separate flip clock page.' },
      { question: 'Can I use the aesthetic Pomodoro timer fullscreen?', answer: 'Yes. Select Fullscreen above the timer. On browsers that cannot enter native fullscreen, the button opens an expanded page view. Use Exit fullscreen or Escape to return.' },
      { question: 'Can I use ambient sounds without starting a timer?', answer: 'Yes. Sound playback is independent of the countdown. Choose a track to start it and select it again to stop. Closing this page stops its ambient player.' },
    ],
    related: ['aesthetic-timer', 'lofi-timer', 'flip-clock', 'fullscreen-timer'],
    finalHeading: 'Make the next round feel inviting',
    finalCopy: 'Choose a task, settle the sound, and start your first 25 minutes.',
  },
  'lofi-timer': {
    ...base,
    keyword: 'Lofi timer',
    secondaryKeywords: ['lofi study timer', 'lofi pomodoro timer'],
    title: 'Lofi Timer — Study with Ambient Sounds | Pomo Cowork',
    description: 'Set up a lofi study timer with rain, wind, fireplace and other ambient sounds. Run a Pomodoro, mix your atmosphere and enter fullscreen.',
    heading: 'A lofi timer for your own study atmosphere',
    intro: 'Set a focus block and build a quiet soundscape around it. Rain, fireplace, wind and other ambient tracks are one click away. Bring your own lofi playlist if you want music.',
    cta: 'Choose your study sound',
    appearance: 'aesthetic',
    experience: 'lofi',
    timerNote: 'Start with a 25/5 Pomodoro. This player contains ambient soundscapes, not a lofi music stream.',
    explanationHeading: 'A lofi study timer with an ambient mixer',
    explanation: [
      'The lofi study setup is often as much about atmosphere as music: a steady countdown, a quiet desk, and a sound you are comfortable leaving in the background. This page puts the existing Pomo Cowork ambient mixer beside a Pomodoro timer so you can choose that atmosphere before starting.',
      'Layer rain with a fireplace, try wind on its own, or keep the entire mix silent. The volume slider controls the combined output. The available tracks are environmental sounds and noise; this page does not supply a licensed lofi music station. A personal playlist can run separately if that is part of your routine.',
      'Treat sound as an option, not a requirement. If a passage or difficult problem needs silence, turn off the active tracks. The countdown keeps running independently, and pausing a session does not unexpectedly stop your chosen ambience.',
    ],
    stepsHeading: 'Set up your lofi Pomodoro',
    steps: ['Pick one reading, revision, or writing task.', 'Choose ambient tracks and adjust the volume before starting.', 'Press Start for a 25-minute focus block or adjust the timer settings.', 'Take a short break and decide whether the next block needs the same soundscape.'],
    benefits: [
      { title: 'An accessible mixer', text: 'Sound choices are visible on the page instead of hidden in the main workspace dock.' },
      { title: 'Layered ambience', text: 'Combine environmental tracks or keep just one playing quietly.' },
      { title: 'Independent playback', text: 'Pause the timer without losing your background atmosphere.' },
    ],
    audience: [
      { title: 'Solo study', text: 'Give an evening of revision a familiar starting routine.' },
      { title: 'Playlist listeners', text: 'Use your own music source with a separate, glanceable countdown.' },
    ],
    faq: [
      { question: 'Does the lofi timer play lofi music?', answer: 'The built-in mixer plays ambient soundscapes such as rain, wind, fireplace, and brown noise. It does not include a lofi music stream. You can play your own playlist separately.' },
      { question: 'Why is the lofi study timer silent when I open it?', answer: 'Sound starts from a deliberate click. Select a sound or use Resume for a saved mix. If a track fails to load or the browser blocks playback, the mixer shows a retry action.' },
      { question: 'Can I mix sounds during a Pomodoro?', answer: 'Yes. Choose multiple tracks and use the master volume to adjust the mix. The audio controls do not change the timer duration or session state.' },
    ],
    related: ['aesthetic-pomodoro-timer', 'reading-timer', 'aesthetic-timer', 'deep-work-timer'],
    finalHeading: 'Set the sound, choose the task',
    finalCopy: 'Give your next study block an atmosphere you can settle into.',
  },
  'fullscreen-timer': {
    ...base,
    keyword: 'Fullscreen timer',
    secondaryKeywords: ['full screen study timer', 'fullscreen pomodoro timer'],
    title: 'Fullscreen Timer — Full Screen Study & Pomodoro | Pomo Cowork',
    description: 'Open a fullscreen study timer with large digits and simple Pomodoro controls. One button expands the timer for a second screen or a quiet focus session.',
    heading: 'Fullscreen timer. Your work gets the whole screen.',
    intro: 'Keep a large countdown beside your notes or on a second monitor. Press Fullscreen to bring only the timer into view, then start when you are ready.',
    cta: 'Open fullscreen controls',
    experience: 'fullscreen',
    timerNote: 'Fullscreen expands the timer without starting it. The default cycle is 25 minutes of work and a five-minute break.',
    explanationHeading: 'A full screen study timer you can read at a glance',
    explanation: [
      'A fullscreen timer makes the current interval the most visible thing on a spare display. The Fullscreen button uses the browser fullscreen feature when available. The timer, task selection, and session controls remain accessible while the surrounding guide and site navigation leave the working area.',
      'Use it as a fullscreen Pomodoro timer for individual study or place it beside a shared question set. Fullscreen changes presentation only: it does not synchronize a class, start a session, or silence other applications. Choose the duration and press Start separately.',
      'Some browsers and embedded views restrict fullscreen. In those cases the same button opens an expanded view within the page and explains the fallback. Exit fullscreen returns to the guide. Escape also closes the expanded view.',
    ],
    stepsHeading: 'Fill your screen with one interval',
    steps: ['Set a focus duration and choose a task.', 'Press the Fullscreen button directly above the timer.', 'Press Start and keep your work beside the display.', 'Use Exit fullscreen or Escape to return to the page.'],
    benefits: [
      { title: 'One clear action', text: 'The Fullscreen button directly opens the timer display.' },
      { title: 'A bigger countdown', text: 'Digits scale to the available screen while controls remain reachable.' },
      { title: 'A practical fallback', text: 'An expanded page view is available when native fullscreen is restricted.' },
    ],
    audience: [
      { title: 'Second monitors', text: 'Keep the interval visible while your primary screen holds the work.' },
      { title: 'Study desks', text: 'Place the countdown beside paper notes without the surrounding article.' },
    ],
    faq: [
      { question: 'How do I make the timer fullscreen?', answer: 'Select Fullscreen above the timer. The button requests fullscreen immediately from your click. Press Start separately when you want the countdown to begin.' },
      { question: 'How do I exit the full screen study timer?', answer: 'Use the visible Exit fullscreen button or Escape. Leaving fullscreen does not cancel a running Pomodoro.' },
      { question: 'Can I use a plain countdown instead?', answer: 'Yes. The exam timer has a one-shot countdown with fullscreen and no Pomodoro break cycle. It is suitable for practice sections or other timed exercises.' },
    ],
    related: ['exam-timer', 'flip-clock', 'minimalist-study-timer', 'aesthetic-pomodoro-timer'],
    finalHeading: 'One screen, one focus block',
    finalCopy: 'Expand the timer and make a clear start.',
  },
  'flip-clock': {
    ...base,
    keyword: 'Flip clock',
    secondaryKeywords: ['online flip clock', 'aesthetic flip clock', 'fullscreen flip clock'],
    title: 'Online Flip Clock — Aesthetic Fullscreen Clock | Pomo Cowork',
    description: 'An online flip clock with animated digits, 12/24-hour format, optional seconds and fullscreen. A quiet desk clock showing your device’s local time.',
    heading: 'An online flip clock for your desk',
    intro: 'Let the time sit quietly beside your work. Split-flap digits, optional seconds, and a fullscreen view give your second screen one simple job.',
    cta: 'View the flip clock',
    experience: 'clock',
    timerNote: 'Shows your device’s local time. Choose a 12-hour display or hide seconds for a quieter clock.',
    explanationHeading: 'A clock for the time of day',
    explanation: [
      'An online flip clock shows the current time with digits inspired by a mechanical split-flap display. Each changing digit turns into place, while unchanged digits stay still. This aesthetic flip clock uses the same calm palette as the Pomo Cowork workspace and adapts to the selected light or dark theme.',
      'The clock reads the time from your device. It is useful on a desk or secondary monitor when you want to notice the hour without opening another application. It is not a countdown or alarm, and it does not record focus sessions. Correct your device time if the display is wrong.',
      'Choose a 12-hour clock if you prefer AM and PM, hide seconds to reduce visual activity, or open the fullscreen flip clock. The animation respects the reduced-motion preference on your device. When you want a timed work interval instead, follow the Pomodoro link below the clock.',
    ],
    stepsHeading: 'Make it your desk clock',
    steps: ['Open the clock and check your device’s local time.', 'Choose 12-hour format or keep the default 24-hour display.', 'Hide seconds if you want fewer digit changes.', 'Select Fullscreen to leave the clock on a spare display.'],
    benefits: [
      { title: 'Time at a glance', text: 'Large split-flap digits keep the hour and minute easy to find.' },
      { title: 'Your preferred format', text: 'Toggle 12-hour time and seconds without changing device settings.' },
      { title: 'Considered motion', text: 'Only changing digits animate; reduced-motion preferences disable the flip.' },
    ],
    audience: [
      { title: 'Desk setups', text: 'Turn an open browser tab into a quiet clock beside your main work.' },
      { title: 'Untimed work', text: 'Keep track of the time of day without committing to a countdown.' },
    ],
    faq: [
      { question: 'Which timezone does the online flip clock use?', answer: 'It shows the local time and date reported by your device. It does not provide a timezone selector or synchronize against an external time server.' },
      { question: 'Can I use the flip clock fullscreen?', answer: 'Yes. Press Fullscreen above the clock. If the browser does not allow native fullscreen, an expanded page view is used instead.' },
      { question: 'Can the flip clock run a Pomodoro?', answer: 'This page shows the time of day. Use the Start a Pomodoro link beneath the clock to open the aesthetic Pomodoro timer with focus and break intervals.' },
    ],
    related: ['aesthetic-pomodoro-timer', 'fullscreen-timer', 'aesthetic-timer', 'reading-timer'],
    finalHeading: 'Give your spare screen a quieter job',
    finalCopy: 'Keep the time in view, then return to what you were doing.',
  },
  'minimalist-study-timer': {
    ...base,
    keyword: 'Minimalist study timer',
    secondaryKeywords: ['simple study timer', 'clean study timer'],
    title: 'Minimalist Study Timer — Simple, Clean Focus | Pomo Cowork',
    description: 'A simple study timer with large digits, your current task and start/pause controls. Keep a real online count nearby and expand the timer to fullscreen.',
    heading: 'A minimalist study timer for the task in front of you',
    intro: 'A large countdown. One task. A place to start and pause. Keep your study screen simple, with a small online count for a little company.',
    cta: 'Open the simple timer',
    experience: 'minimal',
    timerNote: 'Starts with 25/5. Task selection and timer settings remain available; the coworker feed stays out of your study area.',
    explanationHeading: 'Less on screen, a clearer next step',
    explanation: [
      'A minimalist study timer reduces the choices around a focus block. This view keeps the countdown and its actions central, with the current task close by. It leaves out the full coworker feed and appearance controls while keeping timer settings available when a different interval would help.',
      'Before pressing Start, decide what the interval is for. A useful task is specific enough to begin immediately: recall ten definitions, solve two problems, or summarize a section. The default 25-minute block is a starting point; you can shorten or lengthen it in settings.',
      'A small online count shows real connected presence when available. It does not invent study partners or require interaction. For an even quieter display, Fullscreen takes the timer out of the page layout. You can return to the full workspace when you need other tools.',
    ],
    stepsHeading: 'Start with one small study outcome',
    steps: ['Choose one topic and put away unrelated material.', 'Select a current task if you use the task picker.', 'Start the timer or enter Fullscreen first.', 'Pause when interrupted and reset only when you want to abandon the round.'],
    benefits: [
      { title: 'A clean study area', text: 'No coworker list sits beside the digits in this view.' },
      { title: 'Essential controls', text: 'Start, pause, reset, and timer settings remain accessible.' },
      { title: 'Quiet company', text: 'The online count uses actual connection data without a social feed.' },
    ],
    audience: [
      { title: 'Small screens', text: 'Keep the working area centered instead of sharing a row with another panel.' },
      { title: 'Paper-based study', text: 'Let your notes carry the detail while the browser carries the time.' },
    ],
    faq: [
      { question: 'Can I change the simple study timer duration?', answer: 'Yes. Use the timer settings control before starting to choose focus and break lengths. An existing session keeps its timing until it ends or is reset.' },
      { question: 'Is the online count real?', answer: 'Yes. It comes from the app’s connection data. When the connection is unavailable, the page shows a reconnecting message instead of presenting a made-up count.' },
      { question: 'Does this clean study timer still have breaks?', answer: 'Yes. It uses the shared Pomodoro timer with work, short break, and long break controls. For a plain countdown with no break cycle, use the exam timer.' },
    ],
    related: ['fullscreen-timer', 'exam-timer', 'study-timer', 'reading-timer'],
    finalHeading: 'Choose the task. Start the time.',
    finalCopy: 'Your next study block can begin with very little on screen.',
  },
  'deep-work-timer': {
    ...base,
    keyword: 'Deep work timer',
    secondaryKeywords: ['timer for deep work', 'deep focus timer'],
    title: 'Deep Work Timer — 50/10, 60/10 & 90/20 | Pomo Cowork',
    description: 'Choose a deep work timer with 50/10, 60/10 or 90/20 presets. Protect one focused task, plan a break and keep a longer countdown in fullscreen.',
    heading: 'A deep work timer for work that needs room',
    intro: 'Start with 50 minutes of focused work and a ten-minute break. Choose 60/10 or 90/20 when your task needs a longer uninterrupted stretch.',
    cta: 'Choose a deep work block',
    experience: 'deep-work',
    defaults: { workDuration: 50, shortBreak: 10, longBreak: 20, longBreakAfter: 4 },
    timerNote: 'Presets show work / short-break minutes. Choose a preset before starting; active and paused sessions cannot be replaced by a preset.',
    explanationHeading: 'How deep work intervals differ from a classic Pomodoro',
    explanation: [
      'A classic Pomodoro starts with 25 minutes of work and five minutes of rest. A timer for deep work uses longer intervals so a task with a substantial setup cost has more room. Reading a technical argument, designing a system, or writing a difficult section may need time before the useful work begins.',
      'This page offers 50/10, 60/10, and 90/20 presets. The first number is focus time and the second is the short break. None is a universal ideal. Start with 50/10 and choose longer blocks only when they fit your attention, schedule, and the kind of work you are doing.',
      'A deep focus timer marks the boundary; you still need to protect the block. Prepare the relevant material, decide what progress would look like, and leave a note for unrelated requests. At the end, write the next step before taking your break so returning does not require rebuilding the whole context.',
    ],
    stepsHeading: 'Protect a block of focused work',
    steps: ['Define one outcome and prepare the material you need.', 'Choose 50/10, 60/10, or 90/20 before starting.', 'Select your task and start the block, using Fullscreen if helpful.', 'Write a next-step note and take the planned break.'],
    benefits: [
      { title: 'Longer starting intervals', text: '50 minutes is ready on arrival, without a trip through settings.' },
      { title: 'A break in every preset', text: 'Each focus block includes a visible short-break duration.' },
      { title: 'Safe preset changes', text: 'Preset buttons are disabled while a session is active or paused.' },
    ],
    audience: [
      { title: 'Research and analysis', text: 'Keep a sustained question in view while you compare evidence or models.' },
      { title: 'Writing and engineering', text: 'Give a difficult section or implementation enough time to develop.' },
    ],
    faq: [
      { question: 'Which deep work timer preset should I choose?', answer: '50/10 is the starting option. Try 60/10 or 90/20 when your work benefits from a longer block and you have the time available. Shorten the interval if you repeatedly need to stop before it ends.' },
      { question: 'Is a deep focus timer different from Pomodoro?', answer: 'The work-and-break idea is similar. This page starts with longer intervals than the classic 25/5 Pomodoro and exposes presets for changing them quickly.' },
      { question: 'Can I switch to 90/20 during a session?', answer: 'No. Presets are disabled while an active or paused session exists. Finish or reset the current session before choosing another work/break pair.' },
    ],
    related: ['coding-timer', '50-10-pomodoro', '90-minute-timer', 'fullscreen-timer'],
    finalHeading: 'Make room for the difficult part',
    finalCopy: 'Set one outcome and give it an uninterrupted block.',
  },
  'exam-timer': {
    ...base,
    keyword: 'Exam timer',
    secondaryKeywords: ['online exam timer', 'study exam timer'],
    title: 'Online Exam Timer — Simple Fullscreen Countdown | Pomo Cowork',
    description: 'Practice with an online exam timer: set custom minutes, use 30–120 minute presets, pause or reset, and open a large fullscreen countdown without Pomodoro breaks.',
    heading: 'An exam timer for a timed practice paper',
    intro: 'Choose your allotted minutes, open the paper, and start. A large countdown stays in view without automatic breaks or a coworker feed.',
    cta: 'Set your exam countdown',
    experience: 'exam',
    timerNote: 'A one-shot practice countdown with 30, 60, 90, and 120-minute presets. Use the duration field for any whole number from 1 to 1440.',
    explanationHeading: 'Practice pacing with a simple exam countdown',
    explanation: [
      'An online exam timer is useful when you want to rehearse a paper or question set within a fixed time limit. Choose the time allowance from the instructions for your specific practice material. This page does not supply official examination timings or supervise an assessment.',
      'The countdown begins at 60 minutes by default. Use a preset or enter your own whole-minute duration before starting. At zero it stops and shows a visual “Time is up” notice. It does not start another cycle or insert Pomodoro breaks into your practice.',
      'For a realistic rehearsal, prepare the permitted materials and decide in advance whether you will pause for interruptions. Fullscreen keeps the digits large. This is a local browser tool: reloading resets it, and it does not save results, play an alarm, or replace an official exam clock.',
    ],
    stepsHeading: 'Rehearse a timed section',
    steps: ['Read the time allowance in your practice instructions.', 'Choose a preset or enter the required minutes.', 'Enter Fullscreen, prepare your materials, and press Start.', 'Stop when the countdown reaches zero, then review both answers and pacing.'],
    benefits: [
      { title: 'No break cycle', text: 'The countdown ends once instead of moving into a Pomodoro rest period.' },
      { title: 'Custom time allowance', text: 'Set whole minutes to match the material you are practicing.' },
      { title: 'Large, quiet digits', text: 'Fullscreen keeps the countdown visible without social panels.' },
    ],
    audience: [
      { title: 'Practice papers', text: 'Rehearse completing a question set within its stated time allowance.' },
      { title: 'Timed exercises', text: 'Use the same plain countdown for a writing prompt or a short revision quiz.' },
    ],
    advantage: 'Use this page for one timed practice attempt. Move to the shared workspace or exam study guides when you want revision blocks, task organization, and saved focus sessions between practice papers.',
    faq: [
      { question: 'Does the exam timer add Pomodoro breaks?', answer: 'No. It is a one-shot countdown. When the time reaches zero, it stops and displays Time is up. Reset prepares another attempt.' },
      { question: 'Can I enter a custom exam duration?', answer: 'Yes. Enter a whole number between 1 and 1440 minutes before starting. Duration and preset controls lock after starting; reset the timer to change them.' },
      { question: 'Will my exam countdown survive a page reload?', answer: 'No. The practice timer lives in the current tab and resets on reload or navigation. It calculates elapsed time from timestamps while the page remains open, rather than counting interval callbacks.' },
      { question: 'Is this an official exam timer or an alarm?', answer: 'No. It is an independent practice tool with a visual completion notice. Follow your examination provider’s rules and official timing during an actual assessment.' },
    ],
    related: ['study-timer-for-exams', 'fullscreen-timer', 'minimalist-study-timer', 'study-timer'],
    finalHeading: 'Practice the paper and the pacing',
    finalCopy: 'Set the allowed time and give your next attempt a clear boundary.',
  },
  'reading-timer': {
    ...base,
    keyword: 'Reading timer',
    secondaryKeywords: ['timer for reading', 'study reading timer'],
    title: 'Reading Timer — Book Countdown & Stopwatch | Pomo Cowork',
    description: 'Add a book or chapter title, choose a reading countdown or stopwatch, and focus in fullscreen. Use 10, 20 or 30-minute presets for your next reading session.',
    heading: 'A reading timer for one more chapter',
    intro: 'Name the book or chapter, then choose your pace: count down a planned reading block or let the stopwatch measure an open-ended session.',
    cta: 'Set up your reading session',
    experience: 'reading',
    timerNote: 'Starts with a 20-minute countdown. Switch to Stopwatch before starting to count upward instead. The book title stays in this tab.',
    explanationHeading: 'A timer for reading without a page-count target',
    explanation: [
      'A reading timer reserves a stretch of time for a book, article, or chapter. It does not assume every page takes the same effort. A dense argument may deserve a slower session than a familiar story. Choose a time commitment you can keep and use the title field to name the material in front of you.',
      'Countdown is useful when reading needs to fit a schedule. Choose 10, 20, or 30 minutes, or enter a custom duration. Stopwatch is useful when you want to keep reading until a natural stopping point and see how long the session lasted. Pause is available in both modes.',
      'This study reading timer keeps its title and elapsed time only while the page is open. It does not store reading history or estimate words per minute. At the end, write a short summary or bookmark your next starting point elsewhere. Use the main workspace if you want recorded focus sessions attached to a task.',
    ],
    stepsHeading: 'Give your book a little uninterrupted time',
    steps: ['Enter a book, article, or chapter title.', 'Choose Countdown for a fixed block or Stopwatch for an open-ended session.', 'Set the minutes if needed, then press Start.', 'Pause or finish at a sensible point and note where you want to resume.'],
    benefits: [
      { title: 'A named reading session', text: 'The book or chapter stays visible above the time.' },
      { title: 'Two ways to measure', text: 'Choose a planned countdown or count upward with a stopwatch.' },
      { title: 'Room for your text', text: 'Fullscreen gives the timer its own display while the book stays in your hands.' },
    ],
    audience: [
      { title: 'Assigned reading', text: 'Reserve a block for a chapter before reviewing its main ideas.' },
      { title: 'Everyday readers', text: 'Make a modest time commitment without turning pages into a race.' },
    ],
    advantage: 'This page is a lightweight local reading tool. For saved session history, select a reading task in the main workspace and use the shared Pomodoro timer. Your book title here is not uploaded as a task or project.',
    faq: [
      { question: 'Can the reading timer count up instead of down?', answer: 'Yes. Select Stopwatch before starting. It begins at zero and counts elapsed time until you pause or reset. Reset before changing between countdown and stopwatch.' },
      { question: 'Does the timer save my book title or reading history?', answer: 'No. The title and timer state live only in the current page. Reloading or leaving the page clears them. Use a separate reading log or the main workspace for recorded focus sessions.' },
      { question: 'How long should I set a study reading timer for?', answer: 'Choose a block that fits the material and your available time. This page starts at 20 minutes and offers 10 and 30-minute alternatives. You can enter a custom duration before starting.' },
    ],
    related: ['minimalist-study-timer', 'lofi-timer', 'study-timer', 'aesthetic-timer'],
    finalHeading: 'Make a little time for the next page',
    finalCopy: 'Choose your book and let the timer hold the boundary.',
  },
  'coding-timer': {
    ...base,
    keyword: 'Coding timer',
    secondaryKeywords: ['programmer timer', 'focus timer for coding', 'pomodoro for coding'],
    title: 'Coding Timer — 50-Minute Focus, Tasks & Projects | Pomo Cowork',
    description: 'Start a 50-minute coding timer with task selection and a project picker for signed-in users. Choose 50/10, 60/10 or 90/20 and review completed project sessions.',
    heading: 'A coding timer for the next working change',
    intro: 'Choose a task, connect a project when signed in, and start a 50-minute block. Leave enough time to understand the problem before switching context.',
    cta: 'Plan your coding block',
    experience: 'coding',
    defaults: { workDuration: 50, shortBreak: 10, longBreak: 20, longBreakAfter: 4 },
    timerNote: 'Starts at 50/10, with 60/10 and 90/20 presets available before a session. Signed-in users can choose a project for recorded sessions.',
    explanationHeading: 'Pomodoro for coding, with room for context',
    explanation: [
      'A programmer timer is most useful when the interval has a concrete target. Reproduce a bug, trace one request path, implement a small behavior, or review a focused diff. “Work on the app” is too broad to tell you where to begin or whether a block moved the project forward.',
      'This focus timer for coding starts at 50 minutes with a ten-minute short break. Switch to 60/10 or 90/20 before starting if the work needs a longer stretch. The shared task picker remains available, and signed-in users can attach a project through the existing project selector.',
      'Completed sessions linked to a project contribute to its recorded focus totals. Review them in the project journal alongside actual changes and milestones; time alone does not measure code quality. Before a break, leave a note about the next check, failing case, or implementation step so the next block has a clear entry point.',
    ],
    stepsHeading: 'Give the next change a focused block',
    steps: ['Choose a small implementation, investigation, or review target.', 'Select a task and, when signed in, the project it belongs to.', 'Choose a work/break preset and press Start.', 'Leave a restart note at the end and review completed project sessions in the journal.'],
    benefits: [
      { title: '50 minutes ready to go', text: 'Begin with a longer focus block instead of changing the classic 25-minute default.' },
      { title: 'Work has a name', text: 'Keep the current task and project connected to the session.' },
      { title: 'A project trail', text: 'Recorded completed sessions can be reviewed with the project’s progress.' },
    ],
    audience: [
      { title: 'Developers', text: 'Protect an implementation block from frequent context switches.' },
      { title: 'Code reviewers and learners', text: 'Give one diff, exercise, or unfamiliar subsystem a defined investigation window.' },
    ],
    faq: [
      { question: 'What is a good Pomodoro length for coding?', answer: 'This page starts at 50 minutes with a ten-minute break and offers 60/10 and 90/20. Use a shorter block for a small review or a longer one when setup takes time. Choose based on the task rather than treating one interval as mandatory.' },
      { question: 'Can the coding timer track time by project?', answer: 'Signed-in users can choose an existing project before starting. Completed sessions associated with that project contribute to its recorded focus totals, which are available through the project journal.' },
      { question: 'Why can’t I see a project picker?', answer: 'Project selection requires a signed-in account. Guests can still use the timer. Sign in through the main workspace, then return here to choose or create a project.' },
      { question: 'Can I change a project during a coding session?', answer: 'The project picker is locked while a session exists so its attribution stays consistent. Finish or reset the current session before choosing another project.' },
    ],
    related: ['deep-work-timer', 'pomodoro-for-programmers', '50-10-pomodoro', 'fullscreen-timer'],
    finalHeading: 'One block toward a working change',
    finalCopy: 'Name the next step, choose the project, and start the clock.',
  },
} satisfies Record<string, SeoPage>
