import type { SeoSlug } from './seoRoutes'

export interface SeoPage {
  keyword: string
  secondaryKeywords: string[]
  title: string
  description: string
  heading: string
  intro: string
  cta: string
  social: boolean
  defaults: { workDuration: number; shortBreak: number; longBreak: number; longBreakAfter: number }
  timerNote: string
  socialHeading: string
  socialCopy: string
  explanationHeading: string
  explanation: string[]
  stepsHeading: string
  steps: string[]
  benefits: { title: string; text: string }[]
  audienceHeading: string
  audience: { title: string; text: string }[]
  advantageHeading: string
  advantage: string
  faq: { question: string; answer: string }[]
  related: SeoSlug[]
  finalHeading: string
  finalCopy: string
}

// Keywords are editorial targets, not a meta-keywords tag. Each route has its
// own intent, examples and answers; the shared component only owns presentation.
export const seoPages: Record<SeoSlug, SeoPage> = {
  'pomodoro-timer': {
    keyword: 'Pomodoro timer',
    secondaryKeywords: ['25 minute timer', 'Pomodoro technique', 'Pomodoro breaks', 'work and break timer'],
    title: 'Pomodoro Timer with Breaks & Live Company | Pomo Cowork',
    description: 'Start a 25-minute Pomodoro timer, take structured breaks, and work alongside real people. Build a repeatable focus routine with Pomo Cowork in your browser.',
    heading: 'Pomodoro timer for one task at a time',
    intro: 'Give one task 25 minutes. Take a short break, then come back for the next round. Your timer and a little company are right here.',
    cta: 'Start a Pomodoro',
    social: false,
    defaults: { workDuration: 25, shortBreak: 5, longBreak: 15, longBreakAfter: 4 },
    timerNote: 'A classic 25 / 5 cycle, with a 15-minute long break after four focus sessions.',
    socialHeading: 'Your next Pomodoro can have company',
    socialCopy: 'See real focus sessions as people work. Keep your own task and rhythm while sharing the same stretch of time.',
    explanationHeading: 'What is a Pomodoro timer?',
    explanation: [
      'A Pomodoro timer divides work into focus intervals and planned breaks. The familiar starting pattern is 25 minutes of work followed by a five-minute pause. After four focus intervals, take a longer break. The useful part is the agreement you make before pressing Start: one task gets your attention until the interval ends. You do not need to finish an entire project in one round.',
      'Choose something concrete, such as drafting an introduction, checking a spreadsheet, or reading a section of a textbook. If an unrelated thought appears, write a quick reminder and return to the task. At the end of the interval, note where you stopped. A short walk or a drink of water can mark the break before the next round.',
      'Pomo Cowork puts this rhythm into a working browser timer. Focus, short break, and long break controls sit together, and settings let you adjust the durations. The live session list adds company without requiring everyone to do the same work. Treat the pattern as a practical starting point and adapt it to the task in front of you.',
    ],
    stepsHeading: 'Run your first Pomodoro cycle',
    steps: ['Choose one task small enough to make progress on in 25 minutes.', 'Press Start and keep that task in front of you.', 'When focus ends, take the five-minute short break.', 'Return for another round; use the long break after four focus sessions.'],
    benefits: [
      { title: 'A manageable commitment', text: 'Start with one interval instead of trying to promise yourself an entire productive afternoon.' },
      { title: 'Breaks have a place', text: 'A planned pause gives you a clear point to step away and a clear point to return.' },
      { title: 'Visible work units', text: 'Count completed focus sessions to understand how much time a recurring task actually takes.' },
    ],
    audienceHeading: 'A simple rhythm for everyday work',
    audience: [
      { title: 'Writing', text: 'Separate outlining, drafting, and editing into different rounds.' },
      { title: 'Administration', text: 'Give email or paperwork a defined window instead of the whole day.' },
      { title: 'Learning', text: 'Alternate a reading interval with a round of practice questions.' },
    ],
    advantageHeading: 'A Pomodoro timer with a shared workspace',
    advantage: 'Keep the familiar countdown and add live coworkers, task selection, and saved session history through the main workspace. Rooms let a group gather in the same place, while statistics help you review recorded focus time. You can start a timer as a guest; account and Pro features follow the options shown in the app.',
    faq: [
      { question: 'How long is a Pomodoro session?', answer: 'The usual starting point is 25 minutes of focus followed by a five-minute break. This page opens with that pattern and a 15-minute long break after four focus sessions. You can change durations in timer settings when another length fits your work better; an existing session keeps its current timing.' },
      { question: 'What do I do during a Pomodoro break?', answer: 'Choose something that gives the task a pause: stand up, stretch, get water, or look away from the screen. A break does not need its own productivity goal. If checking a feed makes it hard to return, leave that activity for a longer pause after the cycle.' },
      { question: 'Can I pause or reset the timer?', answer: 'Yes. Pause keeps the session available to resume, while Reset stops the current countdown so you can start again. Resetting an unfinished focus session is different from completing it. Use Pause for a temporary interruption and Reset when you want to abandon that round.' },
      { question: 'Do I have to stop at exactly 25 minutes?', answer: 'The interval is a boundary you choose, not a measure of how well you work. If your task consistently needs longer uninterrupted blocks, adjust the duration before starting. Leave a short note when the timer ends so your next session can begin without reconstructing what you were doing.' },
      { question: 'Can I use a Pomodoro timer with other people?', answer: 'Yes. The live list shows people who have active sessions in the current workspace. You can work alongside them on an unrelated task, or use rooms to meet a particular group. For a coordinated cycle with friends, agree on the duration and start time together.' },
    ],
    related: ['25-minute-timer', 'online-pomodoro-timer', 'focus-timer', 'study-timer', 'pomodoro-with-friends'],
    finalHeading: 'One task. One Pomodoro.',
    finalCopy: 'Choose your next small piece of work and give it a focused interval.',
  },
  'study-timer': {
    keyword: 'Study timer',
    secondaryKeywords: ['study Pomodoro timer', 'study and break timer', 'exam study timer', 'study sessions'],
    title: 'Study Timer for Exams, Reading & Revision | Pomo Cowork',
    description: 'Use a study timer for reading, revision, and practice questions. Plan focused sessions and short breaks while studying alongside others on Pomo Cowork.',
    heading: 'Study timer for a clearer study plan',
    intro: 'Turn “study more” into one chapter, one topic, or one set of questions. Start a study block, take a break, and decide what comes next.',
    cta: 'Start a study block',
    social: false,
    defaults: { workDuration: 25, shortBreak: 5, longBreak: 15, longBreakAfter: 4 },
    timerNote: 'Begin with 25 minutes of study and a five-minute break. Adjust the length in settings to suit your material.',
    socialHeading: 'Company for your study desk',
    socialCopy: 'Other people can be working on completely different subjects. The shared part is showing up for a focused session.',
    explanationHeading: 'What is a study timer?',
    explanation: [
      'A study timer gives a learning activity a clear beginning and end. Instead of leaving a textbook open for an unspecified evening, you set aside a block for a specific outcome: understand one concept, answer ten questions, or review a page of notes. A timed session helps you decide what to do now and when to pause. It does not measure how much you have learned on its own.',
      'This timer starts with a 25-minute study block and a five-minute break. That is a convenient first experiment for reading or revision. Before starting, put the materials you need within reach and choose how you will check your understanding. For example, close your notes at the end and explain the main idea in a few sentences.',
      'Use the next block to respond to what you noticed. A difficult topic may need another explanation, while familiar material may be ready for practice questions. Pomo Cowork adds visible live sessions so your study routine can happen alongside other people, even when you are learning independently.',
    ],
    stepsHeading: 'Build a study session around an outcome',
    steps: ['Name the topic and the result you want from this block.', 'Gather your notes, book, or question set before pressing Start.', 'Study until the countdown ends, then check what you understood.', 'Take a break and choose the next topic based on that check.'],
    benefits: [
      { title: 'A smaller study plan', text: 'Replace an overwhelming subject list with one outcome for the next interval.' },
      { title: 'Room for practice', text: 'Assign separate blocks to reading, recall, and questions instead of only rereading notes.' },
      { title: 'A record to reflect on', text: 'Use recorded focus time alongside completed exercises to review your study routine.' },
    ],
    audienceHeading: 'Made for different kinds of learning',
    audience: [
      { title: 'Exam preparation', text: 'Give each topic a block, then revisit the mistakes that need more work.' },
      { title: 'Reading assignments', text: 'Read a section and reserve a few minutes to summarize it.' },
      { title: 'Online courses', text: 'Follow a lesson with a separate session for applying the idea.' },
    ],
    advantageHeading: 'Keep study time connected to actual work',
    advantage: 'Pomo Cowork combines the countdown with tasks, recorded sessions, and a live community. Use the main workspace to organize the work behind your timer, then review the statistics available to your account. If a topic would benefit from company, move into a shared room without turning every study block into a meeting.',
    faq: [
      { question: 'How long should I set a study timer for?', answer: 'Start with a length you can commit to for one clear learning activity. This page uses 25 minutes with a five-minute break. If you keep stopping before the end, try a shorter interval; if you need more time for a practice problem, choose a longer one in settings.' },
      { question: 'Is 50 minutes better than 25 minutes for studying?', answer: 'Neither length is automatically better for every subject or person. A longer block may suit a mock exam section or a difficult problem; a shorter block can be easier to fit between classes. Try each with comparable work and compare understanding and completed tasks, not just minutes.' },
      { question: 'How can I use a timer for exam revision?', answer: 'Choose one topic and a way to check it, such as answering questions without your notes. Use a block to attempt the questions and another to review mistakes. The timer structures the revision period, while the answers tell you which material needs further attention.' },
      { question: 'Does more time on the timer mean better learning?', answer: 'Not necessarily. Time is a useful record of effort, but understanding needs a separate check. Summarize a concept from memory, solve a fresh problem, or explain why an answer is correct. Use the timer to make space for these activities instead of treating a high total as the goal.' },
      { question: 'Can I study alongside people without joining a class?', answer: 'Yes. Pomo Cowork shows live focus sessions, and you can work on your own material alongside the people who are online. There is no shared syllabus required. If you want the same group each time, explore the rooms and account options in the app.' },
    ],
    related: ['pomodoro-timer', 'focus-timer', 'study-with-friends', '50-minute-timer', 'timer-for-studying', 'study-timer-with-friends'],
    finalHeading: 'Choose the topic for your next block',
    finalCopy: 'Open your materials, decide what progress looks like, and start studying.',
  },
  'focus-timer': {
    keyword: 'Focus timer',
    secondaryKeywords: ['deep work timer', 'concentration timer', 'work timer', 'focus sessions'],
    title: 'Focus Timer for Deep Work & Single Tasking | Pomo Cowork',
    description: 'Give one task your attention with a browser focus timer. Set a work interval, plan a break, and find live company for writing, coding, or everyday work.',
    heading: 'Focus timer for the work in front of you',
    intro: 'Close the extra tabs. Choose one outcome. Give it a protected block of time, with a break waiting at the other end.',
    cta: 'Begin a focus session',
    social: false,
    defaults: { workDuration: 50, shortBreak: 10, longBreak: 20, longBreakAfter: 3 },
    timerNote: 'A longer starting rhythm: 50 minutes of focus, ten-minute breaks, and a 20-minute long break after three sessions.',
    socialHeading: 'Independent work, shared presence',
    socialCopy: 'Write, code, design, or plan while other people work on their own tasks. No shared project is required.',
    explanationHeading: 'What is a focus timer?',
    explanation: [
      'A focus timer marks a deliberate window for a single task. You choose what deserves your attention, start the countdown, and postpone unrelated work until the interval ends. Unlike a deadline, the timer does not say the whole task must be finished. It gives you a boundary for making progress and a point at which to review what is left.',
      'This page starts with a 50-minute work interval and a ten-minute break. The longer block leaves space to get into a draft, investigate a bug, or develop an idea. If that feels too long for the task or the time you have, open settings and shorten it before you begin. The best starting interval is one you can use intentionally.',
      'Decide what belongs outside the block as well as inside it. Put incoming requests on a short list, silence optional notifications, and keep only the materials you need nearby. Pomo Cowork supplies the countdown and live company; you supply the boundary. At the end, write the next action before taking your break.',
    ],
    stepsHeading: 'Protect one block of attention',
    steps: ['Write a concrete outcome, such as “draft the opening section”.', 'Keep the 50-minute preset or choose a shorter duration in settings.', 'Press Start and park unrelated requests on a separate list.', 'Leave a next-action note when the timer ends, then take a break.'],
    benefits: [
      { title: 'Fewer task decisions', text: 'Choose the work once, before the interval, instead of reconsidering it every few minutes.' },
      { title: 'Space for complex work', text: 'A longer block gives setup, investigation, and execution a place in the same session.' },
      { title: 'A clean stopping point', text: 'Use the end of the countdown to capture your next action and step away deliberately.' },
    ],
    audienceHeading: 'For work that needs sustained attention',
    audience: [
      { title: 'Developers', text: 'Investigate one bug, implement a small change, or review a pull request.' },
      { title: 'Writers and designers', text: 'Give drafting or exploration a block before switching to feedback.' },
      { title: 'Independent workers', text: 'Reserve a predictable period for client work before checking messages.' },
    ],
    advantageHeading: 'More context than a countdown alone',
    advantage: 'A basic alarm tells you when time is up. Pomo Cowork also lets you attach work to a task, see live coworkers, and review recorded focus sessions in the workspace. Use a room for a recurring work group or keep the public workspace as quiet company while you follow your own schedule.',
    faq: [
      { question: 'What is the difference between a focus timer and a Pomodoro timer?', answer: 'A focus timer can use any work interval you choose. Pomodoro usually refers to a repeating work-and-break pattern, often starting at 25 and five minutes. This page begins with a longer 50-minute focus block and ten-minute break, using the same Pomo Cowork timer and settings.' },
      { question: 'Is a 50-minute focus session too long?', answer: 'It can be, depending on the task and your available attention. The preset is a starting option for work that needs setup and continuity. Shorten it if you are putting off starting, or if a smaller task does not need the full block. Completing a useful step matters more than matching the preset.' },
      { question: 'What should I do if I get distracted during a session?', answer: 'Write down the unrelated thought and return to the chosen task if you can. If an interruption needs immediate attention, pause the timer. Resume when you are ready, or reset the session if the original plan no longer makes sense. A timer does not need to turn interruptions into a penalty.' },
      { question: 'Can I use a focus timer for coding?', answer: 'Yes. Pick a bounded activity such as reproducing a bug, writing one function, or reviewing a specific change. Keep a note of the current hypothesis or next step before a break. That note is particularly useful when returning to work that has several pieces of context.' },
      { question: 'Does this timer block distracting websites?', answer: 'No. The countdown gives your work a time boundary, but it does not block websites or control other applications. Close distracting tabs or use your own device controls if needed. Pomo Cowork adds live presence and session tracking rather than enforcing which tools you can open.' },
    ],
    related: ['45-minute-timer', '50-minute-timer', 'pomodoro-timer', 'online-pomodoro-timer', 'study-with-me', 'online-study-room'],
    finalHeading: 'Make room for the next piece of work',
    finalCopy: 'Pick a useful outcome and begin your protected focus block.',
  },
  'timer-for-studying': {
    keyword: 'Timer for studying',
    secondaryKeywords: ['homework timer', 'timer for homework', 'timed study blocks', 'study break timer'],
    title: 'Timer for Studying & Finishing Homework | Pomo Cowork',
    description: 'Break homework into manageable steps with a timer for studying. Start a short work block, check your progress, and take a break before the next assignment.',
    heading: 'A timer for studying when starting feels hard',
    intro: 'You do not have to finish the whole assignment right now. Open it, choose the first small step, and give that step 15 minutes.',
    cta: 'Start a 15-minute study block',
    social: false,
    defaults: { workDuration: 15, shortBreak: 5, longBreak: 15, longBreakAfter: 4 },
    timerNote: 'Start small: 15 minutes of study and a five-minute break. Use a longer interval when you are ready.',
    socialHeading: 'A little company for homework time',
    socialCopy: 'Your assignment is your own, but the study desk does not have to feel empty. See who is working in the current workspace.',
    explanationHeading: 'How does a timer for studying help organize homework?',
    explanation: [
      'A timer for studying turns an open-ended assignment into a short appointment with one part of the work. “Finish the essay” may be too broad to begin comfortably. “Read the question and write three possible points” tells you what to do during the next interval. The countdown supplies a stopping point so you can check progress before choosing another step.',
      'This page opens with 15 minutes of study and a five-minute break. That short starting block can hold a few homework questions, a paragraph outline, or a review of instructions. You can change the length in settings. For a longer assignment, break the work into preparation, a first attempt, and checking; each part can become its own session.',
      'Before taking a break, leave yourself a clear return point. Write the number of the next exercise or the sentence you want to revise. When the break ends, that note removes another decision. Pomo Cowork adds real people working nearby online, while the timer remains yours to pause, reset, or adapt to the assignment.',
    ],
    stepsHeading: 'Move from assignment to first action',
    steps: ['Open the assignment and read what it actually asks you to produce.', 'Choose a small first action that fits a 15-minute block.', 'Start the timer and work only on that action.', 'Check the result, write down your next step, and take a short break.'],
    benefits: [
      { title: 'Less to start with', text: 'Commit to opening the work and taking one step instead of finishing everything at once.' },
      { title: 'A place for checking', text: 'Make reviewing an answer or proofreading a paragraph its own timed activity.' },
      { title: 'An easier return', text: 'A next-step note gives the following block a clear beginning after your break.' },
    ],
    audienceHeading: 'For the assignment on your desk',
    audience: [
      { title: 'Problem sets', text: 'Attempt a small group of questions, then check your method.' },
      { title: 'Essays', text: 'Separate understanding the prompt, outlining, drafting, and editing.' },
      { title: 'Reading homework', text: 'Read a manageable section and write a short summary before moving on.' },
    ],
    advantageHeading: 'A starting point you can return to',
    advantage: 'The main Pomo Cowork workspace brings tasks and session history together, so another study block can continue an existing piece of work. Live coworkers add a shared sense of activity, and rooms offer a place for a regular homework group. The timer itself is available without setting up a group or an account first.',
    faq: [
      { question: 'What is a good timer length for homework?', answer: 'Choose a duration that fits the next step, not necessarily the whole assignment. This page begins at 15 minutes to make a small first attempt easier to schedule. Once you know what the work involves, you can use settings to choose a longer block for drafting or problem solving.' },
      { question: 'How do I start studying when I keep putting it off?', answer: 'Reduce the first action until it is concrete: open the file, read the instructions, or attempt the first question. Set a short timer for that action and decide what follows after it ends. This is a planning approach, not a guarantee; adjust it if the task needs a different kind of support.' },
      { question: 'Should I use a separate timer for each subject?', answer: 'You can use the same timer and start a fresh session when you change subjects. Name the task clearly so you know what the block is for. Leave a return note for unfinished work before switching, especially if the next subject needs different materials or a different approach.' },
      { question: 'What if I finish my homework before the timer ends?', answer: 'Check that you answered the question and review any uncertain parts. You do not need to invent extra work just to fill the countdown. You can stop the session when you are done; an unfinished countdown that you reset is not treated as a completed Pomodoro.' },
      { question: 'Can I use this timer for studying on a phone?', answer: 'Yes, the page and controls fit a mobile browser. Keep the timer page available while you work and check your device volume if you want an audible alert. Mobile browsers can restrict background activity, so do not rely on a locked phone behaving like a dedicated alarm app.' },
    ],
    related: ['30-minute-timer', 'study-timer', 'pomodoro-timer', 'study-with-friends', 'study-timer-with-friends'],
    finalHeading: 'Start with the first question',
    finalCopy: 'A small, specific step is enough for your next study block.',
  },
  'online-pomodoro-timer': {
    keyword: 'Online Pomodoro timer',
    secondaryKeywords: ['browser Pomodoro timer', 'Pomodoro timer no download', 'free online Pomodoro', 'web Pomodoro timer'],
    title: 'Online Pomodoro Timer — No Download Needed | Pomo Cowork',
    description: 'Open an online Pomodoro timer and start focusing without a download. Use work and break controls, adjust durations, and see live coworkers in your browser.',
    heading: 'Online Pomodoro timer, ready in your browser',
    intro: 'No app installation to get through. Start a 25-minute session here, keep the tab available, and come back for your break.',
    cta: 'Use the online timer',
    social: false,
    defaults: { workDuration: 25, shortBreak: 5, longBreak: 15, longBreakAfter: 4 },
    timerNote: 'Ready for a 25-minute focus session, five-minute short breaks, and a 15-minute long break after four sessions.',
    socialHeading: 'A browser tab with real company',
    socialCopy: 'The live workspace connects your quiet work session to other people online. You can start before deciding whether you want a room or an account.',
    explanationHeading: 'What is an online Pomodoro timer?',
    explanation: [
      'An online Pomodoro timer runs on a web page instead of requiring a separate desktop or mobile app. Open the page, choose a task, and start a timed work interval followed by a break. The usual pattern is 25 minutes of focus and five minutes away from the task, with a longer break after several rounds. All the essential controls are available in the browser.',
      'This makes the timer useful when you move between a laptop, a library computer, and a tablet. You can begin a guest session without installing software or creating an account. For a predictable session, keep the page open and check sound and notification preferences before depending on an alert. Browser and device settings can affect what happens when a tab is hidden or a device sleeps.',
      'Pomo Cowork combines this browser-based timer with a live workspace. Use it as a straightforward countdown, or open the wider app for tasks, rooms, and recorded focus activity. Connected features need an internet connection; starting on the web does not mean every feature will work offline.',
    ],
    stepsHeading: 'Go from browser tab to focus session',
    steps: ['Leave this page open on the device you are using.', 'Check the focus and break lengths with the settings control.', 'Press Start; use Pause or Reset if your plan changes.', 'Take the timed break before beginning another round.'],
    benefits: [
      { title: 'No installation step', text: 'Get to the countdown from a link on a computer or mobile browser.' },
      { title: 'A quick guest start', text: 'Try a focus session before choosing whether to register for account features.' },
      { title: 'Useful tab feedback', text: 'The page title shows the running countdown so the session is easier to find among your tabs.' },
    ],
    audienceHeading: 'For the browser you already have open',
    audience: [
      { title: 'Shared-computer users', text: 'Start a guest timer without installing software on the machine.' },
      { title: 'Remote workers', text: 'Keep a timed work block beside the browser tools you use every day.' },
      { title: 'Occasional timer users', text: 'Bookmark a direct route back to the countdown when you need structure.' },
    ],
    advantageHeading: 'Start simply, then open the workspace',
    advantage: 'Pomo Cowork gives you a browser timer and somewhere to work alongside people. The main workspace adds task organization, chat, session history, and access to statistics and rooms. You can use the basic timer as a guest; the pricing page explains the optional Pro features before you choose them.',
    faq: [
      { question: 'Do I need to download an app to use this Pomodoro timer?', answer: 'No. The timer runs on this page in a browser, and you can start a session from its Start button. Keep the page open while working. You may choose to use other Pomo Cowork features later, but downloading a separate app is not part of starting the basic timer.' },
      { question: 'Can I start without creating an account?', answer: 'Yes, the basic countdown supports guest sessions. An account is useful when you want account-linked history and other workspace features. Rooms and advanced features can have additional requirements, which the app shows when you open them. You do not need to complete registration just to try a focus interval.' },
      { question: 'Will the timer run if I switch browser tabs?', answer: 'The timer uses session timing to update the countdown when you return to the page. However, browsers can limit background processing, sound, and notifications, especially on mobile devices. Keep the tab open and check your alert settings; a sleeping or closed device is not a dependable way to receive an alarm.' },
      { question: 'Does an online Pomodoro timer work without internet?', answer: 'Live coworkers, rooms, and server-backed session records need a connection. A countdown already visible in an open tab should not be treated as a promise that the whole app works offline. Reconnect before relying on shared activity or saved results, and check the app for connection feedback.' },
      { question: 'Is the online timer free?', answer: 'You can start a basic Pomodoro countdown as a guest without paying. Pomo Cowork also offers account and Pro features beyond the basic timer. Check the pricing page for the available plans and included tools rather than assuming that every room or statistics feature is part of the guest experience.' },
    ],
    related: ['pomodoro-timer', 'study-timer', 'focus-timer', 'online-study-room'],
    finalHeading: 'Your next focus session is one click away',
    finalCopy: 'Stay on this page, choose your task, and press Start on the timer.',
  },
  'study-with-me': {
    keyword: 'Study with me',
    secondaryKeywords: ['live study with me', 'study together online', 'virtual study partner', 'study companionship'],
    title: 'Study With Me — Live Focus Sessions Online | Pomo Cowork',
    description: 'Looking for study-with-me company? Start your own timer beside real people studying and working online. No video schedule to follow and no camera needed.',
    heading: 'Study with me, on your own schedule',
    intro: 'Bring your notes and settle in beside people who are working too. Start your own timer whenever you are ready; no camera or video schedule needed.',
    cta: 'Start studying alongside others',
    social: true,
    defaults: { workDuration: 25, shortBreak: 5, longBreak: 15, longBreakAfter: 4 },
    timerNote: 'Your own 25-minute study session, with five-minute breaks. You do not have to match another person’s countdown.',
    socialHeading: 'Meet the people working alongside you',
    socialCopy: 'These are live sessions from the current workspace. When nobody is active, you can be the person who starts the next quiet stretch.',
    explanationHeading: 'What does “study with me” mean here?',
    explanation: [
      'Study with me is a way to give independent study a sense of company. In a video, you might watch another person work at a desk and follow their breaks. In Pomo Cowork, the company comes from real people running their own focus sessions online. You bring your own subject, materials, and goal; the common activity is making time to work.',
      'You do not need to wait for a livestream or join halfway through someone else’s interval. Start your countdown when you are ready, see who else is active, and take a break when your session ends. The live list can include people studying, writing, coding, or doing other focused work. It is a shared workspace rather than a class or a tutoring service.',
      'This format suits moments when working alone feels a little too unstructured, but a conversation would interrupt the task. There is no camera requirement and no expectation that everyone moves at the same speed. If you want a recurring group instead of open-ended company, explore rooms or invite friends to plan a session together.',
    ],
    stepsHeading: 'Settle into a quiet session together',
    steps: ['Put your study material in front of you and pick a small goal.', 'Look at the live sessions to see who is currently working.', 'Start your own timer without waiting for anyone else.', 'Take your break, then return for another session if you want company for the next task.'],
    benefits: [
      { title: 'Company without a call', text: 'Share a period of focused work without turning on a camera or microphone.' },
      { title: 'Your own start time', text: 'Begin when you are ready instead of fitting your day around a broadcast.' },
      { title: 'Different subjects welcome', text: 'Read, revise, or practice while the people beside you follow their own goals.' },
    ],
    audienceHeading: 'For the times you want a study companion',
    audience: [
      { title: 'Solo learners', text: 'Add some company to a course you are taking independently.' },
      { title: 'Students between classes', text: 'Make a short study window feel like a shared appointment.' },
      { title: 'People who prefer quiet', text: 'Work alongside others without a conversation competing with the task.' },
    ],
    advantageHeading: 'Live company you can participate in',
    advantage: 'Your own timer is part of the experience, so you can move from watching others work to running a session yourself. Pomo Cowork adds live activity, rooms, and task tools in the main workspace. There is no prerecorded audience count: the session list reflects the people currently connected to the workspace.',
    faq: [
      { question: 'Is this a study-with-me video or livestream?', answer: 'It is an interactive study workspace rather than a video player. You use your own timer and see live sessions from other people who are working. There is no host’s broadcast to follow, so you can start, pause, and take breaks according to your own study plan.' },
      { question: 'Do I need to turn on my camera?', answer: 'No. Studying alongside people here uses timer activity and the live session list, not a required video call. You can keep your attention on your notes without showing your room or desk. If you want to speak with friends, arrange that separately from the focus timer.' },
      { question: 'Can I join even if I am not a student?', answer: 'Yes. People can use the same workspace for writing, coding, planning, and other focused activities. The company comes from working at the same time, not from studying the same subject. Pick a task that fits your interval and use your timer in the same way.' },
      { question: 'What if nobody is studying online when I arrive?', answer: 'The timer still works, and you can begin your own session. The live area shows an empty state when there are no active sessions rather than filling it with example people. For more predictable company, arrange a time with a friend or a recurring study group.' },
      { question: 'Do I have to follow everyone else’s breaks?', answer: 'No. Each person can keep their own countdown and take a break when it fits their session. That flexibility is useful when people arrive at different times. If you want coordinated breaks, agree on a shared start and duration with friends before beginning the work block.' },
    ],
    related: ['study-with-friends', 'online-study-room', 'study-timer', 'focus-timer'],
    finalHeading: 'Bring your work. There is room to begin.',
    finalCopy: 'Start a study session and share a little quiet working time.',
  },
  'study-with-friends': {
    keyword: 'Study with friends',
    secondaryKeywords: ['study with friends online', 'virtual study group', 'online group study', 'study accountability'],
    title: 'Study With Friends Online, Wherever You Are | Pomo Cowork',
    description: 'Study with friends online using focus sessions and shared rooms. Agree on a goal, work on your own material, and save the conversation for your study break.',
    heading: 'Study with friends, even from different desks',
    intro: 'Agree on a time, bring one goal each, and work quietly together. A shared session can fit different subjects and different places.',
    cta: 'Try a group study block',
    social: true,
    defaults: { workDuration: 25, shortBreak: 5, longBreak: 15, longBreakAfter: 4 },
    timerNote: 'Try a 25-minute group work block and a five-minute check-in. Agree on a start time with your friends.',
    socialHeading: 'Make showing up a shared habit',
    socialCopy: 'See the live workspace below, or open rooms to gather your own group. For a friends-only space, use the room privacy and membership options.',
    explanationHeading: 'What does it mean to study with friends online?',
    explanation: [
      'Studying with friends online means setting aside the same time for independent or shared learning, even when you cannot meet at one table. You might all revise the same course, or one person might write an essay while another solves practice questions. The useful agreement is about how the session works: when you begin, what each person intends to do, and when you will talk again.',
      'Start with a short check-in. Each person names one achievable outcome, then the group works quietly for a timed block. Use the break to compare progress or ask a question. Separating work from conversation helps a friendly session keep its study purpose without requiring everyone to work in exactly the same way.',
      'Pomo Cowork offers timers, live activity, and rooms for gathering in one place. Start with the timer here to try the rhythm, then use the rooms area to arrange your group. Room access depends on its membership and privacy settings, and creating a room follows the account and plan options shown in the app.',
    ],
    stepsHeading: 'Arrange a session your friends can follow',
    steps: ['Agree on a meeting time and choose where your group will gather.', 'Have each person name one goal before the work block.', 'Start 25-minute timers together and save conversation for the break.', 'Compare progress during the break and decide whether to do another round.'],
    benefits: [
      { title: 'A reason to arrive', text: 'A planned session with someone you know makes the start time concrete.' },
      { title: 'Different goals, one meeting', text: 'Keep the shared appointment even when your friends take different courses.' },
      { title: 'Conversation with a boundary', text: 'Use breaks for encouragement or questions while keeping work blocks quiet.' },
    ],
    audienceHeading: 'For the people you already like learning with',
    audience: [
      { title: 'Classmates', text: 'Bring the same assignment and compare questions after a work block.' },
      { title: 'Friends in different cities', text: 'Keep a recurring study appointment without needing the same physical library.' },
      { title: 'Small course groups', text: 'Use a regular meeting time to make steady progress through separate lessons.' },
    ],
    advantageHeading: 'Give your group a place to return to',
    advantage: 'Rooms give a regular group a shared destination, while live session activity makes ongoing work visible. Individual timers let everyone retain control of their own session. Tasks and focus records in the main workspace help each person continue their work between group meetings. Check the room and pricing screens for membership and creation requirements.',
    faq: [
      { question: 'How can I study with friends online?', answer: 'Choose a time, a place to gather, and a work interval everyone accepts. Each person states a goal, starts a timer, and works until the break. In Pomo Cowork, use rooms for a shared destination and the live session list to see activity in your current workspace.' },
      { question: 'Can we study different subjects in the same session?', answer: 'Yes. A shared study session can coordinate time without coordinating the subject. One friend can revise biology while another drafts an essay. State individual goals at the beginning and use the break for a brief check-in, so the group can stay together without forcing identical tasks.' },
      { question: 'How do we keep a group study session from becoming a chat?', answer: 'Decide before starting when conversation will happen. A brief opening check-in and a timed break give everyone a chance to talk without interrupting every work interval. If a discussion needs longer, schedule a separate discussion block instead of stretching a short break indefinitely.' },
      { question: 'Can we have a private room for our friends?', answer: 'Pomo Cowork supports private rooms with membership and access controls. Open the rooms area to see the options available to your account; room creation is offered through the Pro interface. A private room is separate from the public workspace, so use its invitation and membership flow for your group.' },
      { question: 'Will all of our timers start automatically together?', answer: 'Opening the same landing page does not start everyone’s timers or create a shared room. Agree on a start time and begin together, or use the group session options available inside the workspace. Each person remains responsible for checking their own timer and joining the intended room.' },
    ],
    related: ['pomodoro-with-friends', 'study-timer-with-friends', 'online-study-room', 'study-with-me'],
    finalHeading: 'Put the next study date on the calendar',
    finalCopy: 'Invite your friends, choose a goal each, and make time to work together.',
  },
  'pomodoro-with-friends': {
    keyword: 'Pomodoro with friends',
    secondaryKeywords: ['group Pomodoro timer', 'shared Pomodoro sessions', 'Pomodoro together', 'social Pomodoro'],
    title: 'Pomodoro With Friends — Focus & Break Together | Pomo Cowork',
    description: 'Try Pomodoro with friends: agree on a 25-minute work block, focus together, and meet again for a break. Use Pomo Cowork timers and rooms for your next session.',
    heading: 'Pomodoro with friends, one round at a time',
    intro: 'Twenty-five minutes of quiet work. Five minutes to catch up. Repeat the rhythm together, even when everyone has a different task.',
    cta: 'Try a shared Pomodoro round',
    social: true,
    defaults: { workDuration: 25, shortBreak: 5, longBreak: 15, longBreakAfter: 4 },
    timerNote: 'Group rhythm: 25 minutes working, five minutes together on break, then a 15-minute pause after four rounds.',
    socialHeading: 'Share the rhythm, keep your own task',
    socialCopy: 'The live list shows current sessions. Use rooms for your own group and agree on the same cycle before you begin.',
    explanationHeading: 'What is Pomodoro with friends?',
    explanation: [
      'Pomodoro with friends applies the work-and-break rhythm to a group appointment. Everyone chooses a task, agrees on a focus interval, and begins at roughly the same time. When the work block ends, the group takes a break together. The tasks can be unrelated; the shared structure is the reason to show up and the plan for when to stop.',
      'A first session can use 25 minutes of work and five minutes of rest. After four work intervals, take a longer pause. Before starting, decide how many rounds you actually have time for. Two well-planned rounds can be a complete meeting. There is no need to commit to a long session just because the timer supports another cycle.',
      'In Pomo Cowork, each person uses a real timer and can see activity in the shared workspace. Rooms help a recurring group gather in one place. Agree on the start time and break settings together; visiting this page by itself does not synchronize every participant’s controls. Use breaks to check in without turning the focus periods into an ongoing conversation.',
    ],
    stepsHeading: 'Plan a group Pomodoro cycle',
    steps: ['Choose how many rounds the group has time for.', 'Agree on focus and break durations, then name one task each.', 'Start together and keep the focus interval quiet.', 'Meet again during the short break; take a longer pause after four rounds.'],
    benefits: [
      { title: 'A shared stopping point', text: 'Agree when to check in so nobody has to guess whether it is a good moment to interrupt.' },
      { title: 'A meeting with an end', text: 'Choose a round count in advance to make the session fit everyone’s calendar.' },
      { title: 'Support between rounds', text: 'Use a short break to share progress and choose a realistic next task.' },
    ],
    audienceHeading: 'A rhythm for groups doing real work',
    audience: [
      { title: 'Revision partners', text: 'Practice independently, then compare difficult questions on the break.' },
      { title: 'Coworking friends', text: 'Bring separate projects and protect the same time for them.' },
      { title: 'Writing groups', text: 'Draft silently for a round, then share a brief progress update.' },
    ],
    advantageHeading: 'A group routine with a working home',
    advantage: 'The countdown, live session activity, and room tools live in the same app. Friends can work in a shared space and still keep individual tasks and focus records. The wider workspace also offers chat for check-ins. Room creation and advanced features follow the account and Pro options displayed in the app.',
    faq: [
      { question: 'How do you do Pomodoro with a group?', answer: 'Pick the durations and number of rounds first. Each person names a task, starts the focus interval, and saves conversation for the break. Use the break to check progress and prepare the next round. The method works with different tasks as long as everyone understands the agreed work-and-break rhythm.' },
      { question: 'Should everyone use the same Pomodoro duration?', answer: 'Using the same duration makes shared breaks easier to arrange. If some people need a different length, agree on check-in times instead of assuming all countdowns will finish together. Each person controls their own timer, so discuss any change before the next group round begins.' },
      { question: 'What happens if a friend arrives in the middle of a round?', answer: 'They can work quietly until the next agreed break, or begin a separate short session and align with the following round. Avoid interrupting the whole group to restart. A quick message about the next check-in time is usually enough to make the joining plan clear.' },
      { question: 'How many Pomodoros should we do together?', answer: 'Start with a number that fits everyone’s schedule, such as two rounds with a short break between them. Leave time to agree on goals and wrap up. If you plan four rounds, include the longer break in the calendar rather than counting only the focus minutes.' },
      { question: 'Can one person pause the whole group’s timer?', answer: 'Do not assume that pausing your own timer pauses anyone else’s session. Each participant has individual controls. If the group needs to stop together, communicate that explicitly and have everyone check their timer. For an individual interruption, pausing only your own session may be the simpler choice.' },
    ],
    related: ['study-with-friends', 'study-timer-with-friends', 'pomodoro-timer', 'online-study-room'],
    finalHeading: 'Choose your next round together',
    finalCopy: 'One task each, one agreed start, and a break to look forward to.',
  },
  'study-timer-with-friends': {
    keyword: 'Study timer with friends',
    secondaryKeywords: ['group study timer', 'shared study timer', 'study timer for groups', 'timed group study'],
    title: 'Study Timer With Friends for Group Sessions | Pomo Cowork',
    description: 'Use a study timer with friends to plan quiet work blocks and group check-ins. Set a shared rhythm, keep individual goals, and study together in Pomo Cowork.',
    heading: 'A study timer with friends and a plan for the hour',
    intro: 'Give your study group a simple agenda: a goal each, a quiet work block, and a short check-in. Keep the timer visible while you work.',
    cta: 'Try the group study timer',
    social: true,
    defaults: { workDuration: 25, shortBreak: 5, longBreak: 15, longBreakAfter: 4 },
    timerNote: 'Two 25-minute study blocks plus two five-minute breaks fill an hour. Set aside extra time for introductions if needed.',
    socialHeading: 'Know when your group is working',
    socialCopy: 'Live sessions make ongoing work visible. Open a room to gather friends in the same space, then check that everyone has the intended duration.',
    explanationHeading: 'What is a study timer with friends for?',
    explanation: [
      'A study timer with friends gives a group meeting an agenda people can follow without constant reminders. It answers a practical question: are we working now, or is this the time to discuss a problem? The group agrees on the timing, and each person chooses what to achieve during the work block. That distinction is useful when a study meeting needs both quiet effort and conversation.',
      'For a one-hour plan, try two 25-minute blocks with two five-minute breaks. Use the first block to attempt questions or prepare a draft. During the break, identify what needs attention. The second block can address those gaps. Arrange introductions before the hour or shorten the blocks so the meeting fits the time you actually have.',
      'Pomo Cowork provides the timer, live session visibility, and rooms for gathering your group. Each student keeps an individual task and countdown. Opening the same page does not automatically link all controls, so agree on when to start and how to handle late arrivals. A clear plan is more useful than expecting identical progress from everyone.',
    ],
    stepsHeading: 'Turn one hour into a group study plan',
    steps: ['Agree on an end time and leave room for the opening check-in.', 'Choose a task each and check everyone’s timer settings.', 'Run the first quiet study block, then discuss what needs attention.', 'Use the second block for the next step and finish with a brief progress check.'],
    benefits: [
      { title: 'An agenda everyone sees', text: 'Work intervals and breaks give the meeting a structure without repeated announcements.' },
      { title: 'Individual progress stays visible', text: 'Each person can choose an achievable goal instead of matching the fastest learner.' },
      { title: 'Questions get a time slot', text: 'Collect questions during focus and use the next check-in to decide which to discuss.' },
    ],
    audienceHeading: 'For study groups with limited time',
    audience: [
      { title: 'Weekly homework groups', text: 'Use the same simple agenda each week while the assignments change.' },
      { title: 'Exam practice partners', text: 'Attempt questions independently before comparing approaches.' },
      { title: 'Project classmates', text: 'Give each person a separate task and a planned time to report progress.' },
    ],
    advantageHeading: 'Keep timing, presence, and tasks together',
    advantage: 'Instead of posting occasional timer updates in a chat, your group can see active sessions in Pomo Cowork. Rooms provide a common destination, and the main workspace lets each person organize tasks and review recorded time. Use the app’s room access and plan options when setting up a recurring group.',
    faq: [
      { question: 'How do we use a study timer for a one-hour group session?', answer: 'Two 25-minute focus blocks and two five-minute breaks total one hour. If you need introductions or a longer wrap-up, start those earlier or shorten a work block in settings. Decide the schedule before starting so the meeting does not run past the time everyone agreed to.' },
      { question: 'Is this one shared countdown or an individual timer for each student?', answer: 'Each student controls an individual timer. The live workspace makes other sessions visible, but loading this page does not automatically connect everyone’s Start and Pause buttons. For a common rhythm, choose the same durations and start together in the room or workspace your group has agreed to use.' },
      { question: 'Can friends join the study group from different time zones?', answer: 'Yes, provided you agree on the same actual meeting time. Include a time zone in your invitation or use a calendar event that converts it for each person. The countdown length is the same everywhere; the part that needs coordination is when the group intends to begin.' },
      { question: 'What should we do if someone needs help during a focus block?', answer: 'Agree on a rule before starting. For example, note ordinary questions for the next break, but interrupt for a problem that prevents any progress. If a question needs a long explanation, make a separate discussion block so other group members can keep their planned work time.' },
      { question: 'Can we keep separate study goals in the same room?', answer: 'Yes. A common room or start time does not require everyone to select the same task. Choose goals that fit the interval and use the check-in to describe progress. The timer organizes the group’s time while each person remains responsible for their own material and next step.' },
    ],
    related: ['study-with-friends', 'pomodoro-with-friends', 'study-timer', 'timer-for-studying'],
    finalHeading: 'Give your next study hour a clear shape',
    finalCopy: 'Agree on the plan, gather your friends, and begin the first block.',
  },
  'online-study-room': {
    keyword: 'Online study room',
    secondaryKeywords: ['virtual study room', 'study room online', 'online study space', 'virtual library'],
    title: 'Online Study Room with Timers & Live Company | Pomo Cowork',
    description: 'Find an online study room for quiet work alongside others. Try a focus timer, see live sessions, and explore shared or private rooms for your study routine.',
    heading: 'An online study room for your next quiet hour',
    intro: 'Bring your own work to a shared online space. Start with the timer here, then explore rooms when you want a regular place to meet.',
    cta: 'Begin a quiet study session',
    social: true,
    defaults: { workDuration: 50, shortBreak: 10, longBreak: 20, longBreakAfter: 3 },
    timerNote: 'Settle in for 50 minutes, followed by a ten-minute break. Shorten the session in settings if you have less time.',
    socialHeading: 'A shared desk, wherever you are',
    socialCopy: 'See sessions in the current workspace below. To enter a particular study room, open the room directory and follow its access options.',
    explanationHeading: 'What is an online study room?',
    explanation: [
      'An online study room is a shared digital place where people meet to spend time on their own learning tasks. Think of the useful part of a library table: other people are present, there is a reason to settle in, and everyone can have different material in front of them. The room supplies a meeting place rather than a lesson or a promise of tutoring.',
      'Pomo Cowork combines that shared presence with individual focus timers and live session activity. You can try a quiet block from this page before choosing a room. The room directory offers the spaces available to you; joining a specific room follows its sign-in, privacy, and membership requirements. A public workspace and a private group room serve different purposes, so choose the setting that matches how you want to study.',
      'For a longer visit, this page starts with 50 minutes of focus and a ten-minute break. Bring a chapter, an exercise set, or an online lesson, and define a small outcome before starting. If you want dependable company at a particular time, arrange a recurring visit with friends instead of assuming every room will always be occupied.',
    ],
    stepsHeading: 'Make yourself a place to study',
    steps: ['Try the timer here or browse rooms for a specific shared space.', 'Follow the selected room’s sign-in and membership steps.', 'Choose a learning goal and start your own focus session.', 'Take a break and leave a next-step note before another block.'],
    benefits: [
      { title: 'A destination for study time', text: 'Return to a familiar online place when it is time to work on your material.' },
      { title: 'Quiet shared presence', text: 'See others working without requiring everyone to join a video call.' },
      { title: 'A choice of company', text: 'Use the open workspace for casual company or arrange a room with a regular group.' },
    ],
    audienceHeading: 'For people missing a shared study space',
    audience: [
      { title: 'Distance learners', text: 'Give independent online coursework a regular place in your day.' },
      { title: 'Students studying at home', text: 'Create a study appointment even when you cannot get to the library.' },
      { title: 'Recurring study groups', text: 'Meet in one room while each member follows a separate learning plan.' },
    ],
    advantageHeading: 'A room with tools for the time you spend there',
    advantage: 'Pomo Cowork connects room-based company with timers, tasks, and focus activity. The main workspace offers chat and recorded sessions, with statistics available according to your account. Room privacy and membership controls help groups manage access; the room and pricing screens explain what you need to join or create a space.',
    faq: [
      { question: 'How do I join an online study room?', answer: 'Open the room directory and choose a room available to you. Follow the sign-in and membership prompts for that room. This landing page lets you try the timer first, but starting it does not automatically make you a member of a private room or create a new room.' },
      { question: 'Is an online study room a video call?', answer: 'Not in this experience. Pomo Cowork uses focus timers, live session activity, and room tools to provide a shared working space. A camera is not required to run a session alongside others. If your group wants a separate voice or video conversation, arrange that independently.' },
      { question: 'What is the difference between public and private study rooms?', answer: 'Public rooms can be discoverable in the room directory, while private rooms use access and membership restrictions. The default shared workspace is another place to work alongside people. Check the chosen room’s privacy and joining controls before inviting friends or deciding what task information to share.' },
      { question: 'Can I create a study room for my own group?', answer: 'The rooms screen offers room creation through the Pro interface. Check the current account and plan options there, then choose the room’s name and privacy setting. Creating a room and inviting people are separate steps from starting the timer on this page; use the room’s membership tools to organize access.' },
      { question: 'Are there always people in the study room?', answer: 'Availability depends on who is connected and running a session at that moment. Pomo Cowork shows real activity and an empty state when nobody is active. If you need company at a fixed time, invite a friend or arrange a recurring group session rather than relying on a room being continuously occupied.' },
    ],
    related: ['study-with-me', 'study-with-friends', 'study-timer-with-friends', 'focus-timer', '50-minute-timer', 'online-pomodoro-timer'],
    finalHeading: 'Settle in for a quiet block of work',
    finalCopy: 'Bring one learning goal and make the next stretch of time your own.',
  },
  '50-minute-timer': {
    keyword: '50 minute timer',
    secondaryKeywords: ['50 minute study timer', '50 minute countdown', '50 minute focus timer', '50 10 study timer'],
    title: '50 Minute Timer for Studying & Focus Time | Pomo Cowork',
    description: 'Start a 50 minute timer for studying, writing, or focused work. Follow your countdown with a ten-minute break and work alongside live coworkers in your browser.',
    heading: '50 minute timer for one uninterrupted work block',
    intro: 'Ready for a longer stretch? Your countdown is set to 50 minutes. Choose one task, press Start, and leave the next ten minutes for a break.',
    cta: 'Start your 50-minute block',
    social: false,
    defaults: { workDuration: 50, shortBreak: 10, longBreak: 20, longBreakAfter: 3 },
    timerNote: 'A 50-minute countdown with a ten-minute short break and a 20-minute long break after three focus sessions.',
    socialHeading: 'Spend the next 50 minutes in good company',
    socialCopy: 'See real people working in the current workspace. Your interval can be longer or shorter than theirs; everyone keeps their own timer.',
    explanationHeading: 'What can you do with a 50 minute timer?',
    explanation: [
      'A 50 minute timer gives you a defined block for work that needs more room than a quick sprint. You might read a chapter and summarize it, draft a section of an essay, or work through a set of practice problems. Decide on a specific outcome before you start so the countdown measures a deliberate activity rather than simply time spent at your desk.',
      'Pairing 50 minutes of work with a ten-minute break makes a one-hour cycle. That can fit a gap between classes or a reserved hour in your calendar. Keep preparation outside the countdown when possible: open your materials, get water, and decide where to put unrelated thoughts. At the end, write a short note about your next action before stepping away.',
      'This page opens the real Pomo Cowork timer at 50 minutes when you do not already have a session running. You can pause an interruption, reset an abandoned attempt, or change the duration in settings. Fifty minutes is an option for planning your time, not a requirement to keep working when a shorter interval would suit you better.',
    ],
    stepsHeading: 'Plan a useful 50-minute session',
    steps: ['Choose an outcome that fits a longer work block and open the materials you need.', 'Check that the timer shows 50:00, then press Start.', 'Keep unrelated tasks on a separate list until the countdown finishes.', 'Take a ten-minute break and decide whether another block is useful.'],
    benefits: [
      { title: 'A block that fits the hour', text: 'Leave 50 minutes for the task and ten for a short break before your next commitment.' },
      { title: 'Time to get past setup', text: 'Keep reading, reasoning, and a first attempt together when switching tasks would interrupt your progress.' },
      { title: 'A deliberate review point', text: 'Use the end of the interval to check what you completed and choose the next action.' },
    ],
    audienceHeading: 'For a longer stretch at your desk',
    audience: [
      { title: 'Students with a free period', text: 'Use an available hour for practice or reading, with a break before the next class.' },
      { title: 'Writers drafting a section', text: 'Give one part of a draft a full block before switching to editing.' },
      { title: 'People solving a complex problem', text: 'Make space to understand the problem, try an approach, and record what you found.' },
    ],
    advantageHeading: 'A longer countdown inside a shared workspace',
    advantage: 'Pomo Cowork combines your 50-minute session with live company, task selection, and recorded focus activity. Open the main workspace to organize the tasks behind your time, or explore rooms for a regular study group. The basic countdown works as a guest; account and Pro features keep their existing access requirements.',
    faq: [
      { question: 'How do I set the timer to exactly 50 minutes?', answer: 'Open this page with no active session and the timer starts at 50:00. Press Start to begin the countdown. If you already have a running or paused session, it keeps its timing. Finish or reset it before changing the focus duration to 50 minutes in settings.' },
      { question: 'Does a 50-minute timer include the break?', answer: 'The focus countdown itself lasts 50 minutes. The short break is a separate ten-minute interval, so a complete work-and-break cycle takes one hour. After three completed focus sessions, this preset uses a longer 20-minute break. You can adjust these lengths in settings before starting.' },
      { question: 'Is 50 minutes a good length for a practice exam?', answer: 'Use it if 50 minutes matches the section or exercise you want to practice. For an official timed format, follow the duration specified in your exam instructions instead of this preset. The timer structures your practice period; it does not assess answers or enforce exam conditions.' },
      { question: 'Can I pause the 50-minute countdown and continue later?', answer: 'Yes. Pause keeps the remaining time available for you to resume. Use it when a brief interruption needs attention, and choose Reset if you want to abandon the attempt. If you are simulating an exam, decide in advance whether pausing fits the conditions you intend to practice.' },
      { question: 'What should I do after 50 minutes of studying?', answer: 'Leave a note about what you finished and where you want to continue. Then take the ten-minute break: step away, get water, or stretch. Decide whether the next block should continue the topic or check your understanding through a different activity, such as answering questions without notes.' },
    ],
    related: ['45-minute-timer', 'study-timer', 'focus-timer', 'pomodoro-timer', 'timer-for-studying', 'online-study-room'],
    finalHeading: 'Give the next 50 minutes a clear purpose',
    finalCopy: 'Open your task, settle in, and begin a longer focus session.',
  },
  '25-minute-timer': {
    keyword: '25 minute timer',
    secondaryKeywords: ['25 minute countdown', '25 minute Pomodoro timer', '25 minute study timer', '25 5 timer'],
    title: '25 Minute Timer for a Focused Work Sprint | Pomo Cowork',
    description: 'Start a 25 minute timer for one focused task, then take a five-minute break. Use a real Pomodoro countdown with live company for studying or everyday work.',
    heading: '25 minute timer for your next small win',
    intro: 'One focused sprint can fit into a busy day. Pick a task you can move forward in 25 minutes, press Start, and keep five minutes for yourself afterward.',
    cta: 'Begin a 25-minute sprint',
    social: false,
    defaults: { workDuration: 25, shortBreak: 5, longBreak: 15, longBreakAfter: 4 },
    timerNote: '25 minutes of focus plus a five-minute short break. After four focus sessions, the long break is 15 minutes.',
    socialHeading: 'Someone else is making a start, too',
    socialCopy: 'See live sessions in the current workspace while you tackle your own task. Your short sprint can happen alongside someone else’s longer project.',
    explanationHeading: 'What fits into a 25 minute timer?',
    explanation: [
      'A 25 minute timer counts down a short, deliberate period of attention. It is the familiar work interval used in a classic Pomodoro cycle, but you can also use it once without planning a whole afternoon of rounds. Choose a small outcome: make a rough outline, review a page of vocabulary, or sort the documents for one application. The timer marks the boundary around that attempt.',
      'With a five-minute break afterward, one sprint fits into half an hour. That makes it practical for a gap before a meeting or the first part of an evening study session. Prepare your materials before pressing Start and leave optional messages until the break. If the task turns out to be bigger than expected, record the next step instead of treating the unfinished work as a failed session.',
      'This page presets the Pomo Cowork countdown to 25 minutes when no session is already active. Pause if you need to deal with an interruption, or reset when you want a fresh attempt. You can stay for another round or stop after one useful piece of progress.',
    ],
    stepsHeading: 'Use a spare half-hour deliberately',
    steps: ['Choose a small outcome, such as outlining three points or reviewing ten terms.', 'Open the materials and check that the idle timer shows 25:00.', 'Press Start and keep this sprint for the chosen task.', 'Write down where you stopped and take the five-minute break.'],
    benefits: [
      { title: 'A sprint you can schedule', text: 'A 25-minute task and five-minute pause fit a single half-hour slot.' },
      { title: 'A smaller first commitment', text: 'Give a task one attempt before deciding how much more time it needs.' },
      { title: 'A useful handoff to yourself', text: 'Capture the next action at the end so a second sprint has a clear starting point.' },
    ],
    audienceHeading: 'For small tasks and first attempts',
    audience: [
      { title: 'Students reviewing notes', text: 'Pick a small topic and finish with a few questions from memory.' },
      { title: 'Writers finding an opening', text: 'Try a rough paragraph without asking the first draft to be perfect.' },
      { title: 'People between meetings', text: 'Finish one contained task while leaving a short transition before the next call.' },
    ],
    advantageHeading: 'A short sprint with somewhere to continue',
    advantage: 'Use the guest timer for a quick start, then open the Pomo Cowork workspace when you want to connect sessions to tasks and review recorded work. Live activity adds company for a single sprint as well as a longer routine. Rooms offer a place for recurring partners, subject to the app’s account and plan options.',
    faq: [
      { question: 'Is a 25-minute countdown the same as a full Pomodoro cycle?', answer: 'The countdown covers one focus interval. A complete work-and-break cycle also includes the five-minute short break, for a total of 30 minutes. If you repeat the pattern, this preset uses a 15-minute long break after four focus sessions. You can also do just one interval.' },
      { question: 'Can I do useful work in only 25 minutes?', answer: 'Choose a result small enough to attempt in that time: outline a section, answer several practice questions, or review one document. A large project may need many intervals. Use the sprint to produce a concrete next step rather than expecting the whole project to be finished.' },
      { question: 'How much time should I leave for four 25-minute sessions?', answer: 'Four focus intervals total 100 minutes. Add three five-minute breaks between them and a 15-minute break after the fourth, and the full sequence takes 130 minutes. Preparation and any interruptions take additional time. Plan fewer rounds if you only have an hour available.' },
      { question: 'Should I choose 25 or 30 minutes for a work block?', answer: 'Choose 25 minutes when you want work and a five-minute break to fit into half an hour. Choose 30 minutes when you want the full half-hour for the task and can take a break afterward. Neither duration guarantees better work; match the interval to your available time.' },
      { question: 'Why might this page show a different time when I open it?', answer: 'If you already have a running or paused session, opening another timer page preserves that session. A fresh idle visit uses the 25-minute preset. To change an existing plan, finish or reset the current countdown and set the focus duration to 25 minutes in settings.' },
    ],
    related: ['pomodoro-timer', '30-minute-timer', 'study-timer', 'online-pomodoro-timer'],
    finalHeading: 'What could you move forward in 25 minutes?',
    finalCopy: 'Pick a small outcome and give it your next focused sprint.',
  },
  '30-minute-timer': {
    keyword: '30 minute timer',
    secondaryKeywords: ['half hour timer', '30 minute countdown', '30 minute study timer', '30 minute work timer'],
    title: '30 Minute Timer for Study & Everyday Tasks | Pomo Cowork',
    description: 'Set aside half an hour with a 30 minute timer. Work through homework, clear a small task batch, or practice a skill with live company and a break afterward.',
    heading: '30 minute timer for a half-hour commitment',
    intro: 'Have half an hour for homework, practice, or unfinished admin? Give the whole block to that activity and choose what comes next when the timer ends.',
    cta: 'Start a half-hour session',
    social: false,
    defaults: { workDuration: 30, shortBreak: 5, longBreak: 15, longBreakAfter: 4 },
    timerNote: 'A full 30 minutes for your task, followed by a separate five-minute break. The long break is 15 minutes after four sessions.',
    socialHeading: 'Share the next half-hour with other workers',
    socialCopy: 'Keep your own task while real people work beside you online. You do not have to match their subject or start time to use the shared space.',
    explanationHeading: 'How can you use a 30 minute timer?',
    explanation: [
      'A 30 minute timer gives an activity a full half-hour window. It works for a single task or a small batch of related work, such as checking several homework answers, organizing receipts, or practicing vocabulary. Decide what belongs in the batch before starting. Otherwise, small tasks can keep multiplying until the original plan disappears.',
      'Unlike a 25-minute sprint followed by a five-minute break, this countdown spends all 30 minutes on the activity itself. The optional short break comes afterward, so allow 35 minutes for both work and rest. If you have a hard deadline at the half-hour mark, include any packing up or review within the work interval rather than expecting extra time at the end.',
      'Use the last part of your session to check what you accomplished and decide what should wait. The Pomo Cowork timer starts at 30:00 on an idle visit and gives you pause, reset, and duration settings. Visible coworkers can provide company, but the scope of the session stays yours: one half-hour, one chosen activity, and a clear point to reassess.',
    ],
    stepsHeading: 'Give half an hour a specific job',
    steps: ['Choose one activity or list a small batch of closely related tasks.', 'Reserve 30 minutes for work and extra time afterward if you want a break.', 'Start the countdown and avoid adding unrelated jobs to the batch.', 'Check the result before you finish, then take a five-minute pause.'],
    benefits: [
      { title: 'A familiar calendar block', text: 'Reserve a half-hour for a task and know exactly where the work period ends.' },
      { title: 'A limit for small-task batches', text: 'Give messages or paperwork a bounded window instead of letting them occupy the afternoon.' },
      { title: 'Practice with a finish line', text: 'Return to a skill for a defined session, then decide what to practice next time.' },
    ],
    audienceHeading: 'For practical half-hour sessions',
    audience: [
      { title: 'Homework finishers', text: 'Use a session to check answers, correct mistakes, and prepare an assignment to submit.' },
      { title: 'Language learners', text: 'Combine a short exercise with reviewing the words that caused difficulty.' },
      { title: 'People catching up on admin', text: 'Handle a planned set of messages, forms, or receipts before returning to other work.' },
    ],
    advantageHeading: 'Connect small tasks to the time they take',
    advantage: 'A half-hour session can become part of a longer project in the Pomo Cowork workspace. Use task selection and recorded sessions to connect your countdown to actual work, with statistics available according to your account. Live coworkers and shared rooms add company when routine admin or independent practice feels solitary.',
    faq: [
      { question: 'Does this half-hour timer count up or down?', answer: 'This page opens a countdown from 30:00 to zero when there is no existing session. It is preset for a fixed work interval, rather than an open-ended stopwatch. You can pause and resume the remaining time, or reset the session if you decide to start over.' },
      { question: 'Is the five-minute break included in the 30 minutes?', answer: 'No. The work interval lasts 30 minutes, and the short break is another five minutes afterward. Together they take 35 minutes. If you need work and rest to fit inside a half-hour appointment, use the 25-minute timer with its five-minute break instead.' },
      { question: 'Can I use 30-minute blocks instead of classic Pomodoros?', answer: 'Yes. You can organize work into 30-minute intervals with planned pauses between them. That differs from the familiar 25-minute Pomodoro starting pattern, but the basic planning idea still applies. Choose a duration you have time for and review whether it fits the tasks you actually do.' },
      { question: 'How do I keep a half-hour admin session from running over?', answer: 'List the small jobs you intend to handle before starting and avoid adding unrelated requests as they arrive. Leave time within the interval to save your work and record anything unfinished. When the countdown ends, choose explicitly whether the remaining jobs need another session or can wait.' },
      { question: 'Can I use two 30-minute timers for an hour of study?', answer: 'Two focus intervals add up to 60 minutes of study. Breaks increase the total elapsed time: with a five-minute pause between them, you need 65 minutes before any final break. If the entire appointment must last one hour, shorten a block or use a different work-and-break plan.' },
    ],
    related: ['25-minute-timer', '45-minute-timer', 'timer-for-studying', 'focus-timer', 'study-timer'],
    finalHeading: 'Give half an hour to the task you chose',
    finalCopy: 'Define the activity, clear a little space, and begin your countdown.',
  },
  '45-minute-timer': {
    keyword: '45 minute timer',
    secondaryKeywords: ['45 minute study timer', '45 minute countdown', '45 minute focus session', 'three quarter hour timer'],
    title: '45 Minute Timer for Study & Longer Work Blocks | Pomo Cowork',
    description: 'Use a 45 minute timer for reading, drafting, or practice. Give a longer task room to develop, then take a ten-minute break alongside the Pomo Cowork community.',
    heading: '45 minute timer for work that needs room to develop',
    intro: 'Move beyond setup and into the task. Spend three quarters of an hour reading, drafting, or practicing, then step away for a planned break.',
    cta: 'Begin a 45-minute work block',
    social: false,
    defaults: { workDuration: 45, shortBreak: 10, longBreak: 20, longBreakAfter: 3 },
    timerNote: '45 minutes of focus, a ten-minute short break, and a 20-minute long break after three focus sessions.',
    socialHeading: 'Keep company through a longer session',
    socialCopy: 'Settle into your own material while the current workspace shows other people focusing. For a recurring study appointment, explore a shared room.',
    explanationHeading: 'When does a 45 minute timer make sense?',
    explanation: [
      'A 45 minute timer marks three quarters of an hour for a task that needs some preparation and a sustained attempt. It can hold a reading session with notes, a first draft of a longer answer, or a rehearsal followed by revision. Choose an outcome with enough substance for the block, while leaving yourself permission to stop and rethink an approach that is not working.',
      'This length leaves some space around a one-hour appointment. With a ten-minute break, the work-and-rest sequence takes 55 minutes, leaving five minutes for preparation or a brief check-in. That can be useful for a study meeting where you want quiet work and a little conversation without filling every minute with the countdown.',
      'Pomo Cowork presets an idle timer to 45 minutes on this page. Bring the materials you need, decide how you will review the result, and press Start. The live session list offers company while individual timers remain independent. At the end, use a short note or checklist to capture your progress so a later session can continue without repeating the setup.',
    ],
    stepsHeading: 'Plan a longer attempt and a short review',
    steps: ['Choose an outcome, such as drafting an answer or reading and summarizing a section.', 'Prepare the materials and check that your idle timer shows 45:00.', 'Start the session, keeping review time inside the work block.', 'Save the result and take a ten-minute break before choosing the next task.'],
    benefits: [
      { title: 'Room for preparation and practice', text: 'Understand the material and attempt something with it during the same work block.' },
      { title: 'A little margin around the hour', text: '45 minutes of work and ten of rest leave five minutes for setup or a check-in.' },
      { title: 'A result you can review', text: 'Plan to finish with a draft, summary, or attempt that shows what needs attention next.' },
    ],
    audienceHeading: 'For study and work with several connected steps',
    audience: [
      { title: 'Readers taking notes', text: 'Read a substantial section and put the main ideas into your own words.' },
      { title: 'Students practicing longer answers', text: 'Plan an approach, write the answer, and reserve time to check its structure.' },
      { title: 'Presenters rehearsing', text: 'Run through a presentation and revise the parts that need clearer explanations.' },
    ],
    advantageHeading: 'A longer session with a record of the work',
    advantage: 'Pair the countdown with a task in Pomo Cowork so a later session has a clear subject to return to. The main workspace brings together recorded sessions, live activity, and access to focus statistics. When you want a recurring practice partner, room tools provide a shared destination under the app’s existing membership and plan rules.',
    faq: [
      { question: 'How long is 45 minutes in hours and seconds?', answer: '45 minutes is three quarters of an hour, or 2,700 seconds. The timer displays that work period as 45:00 at the start of an idle session. Its ten-minute short break is separate, so the complete work-and-break sequence takes 55 minutes rather than 45.' },
      { question: 'How can I fit a 45-minute study block into a one-hour meeting?', answer: 'Use five minutes to agree on goals and prepare, 45 minutes for quiet work, and ten minutes for a break or check-in. Those parts add up to one hour. Decide whether discussion belongs in the final ten minutes so it does not unexpectedly interrupt the work interval.' },
      { question: 'Should I use 45 or 50 minutes for reading?', answer: 'Use the length that fits your schedule and the amount of material you plan to tackle. A 45-minute block leaves more margin inside an hour; a 50-minute block uses more of that time for reading. Include a short summary in either plan so the countdown ends with something you can review.' },
      { question: 'Can I time a presentation rehearsal for 45 minutes?', answer: 'Yes, if that is the practice window you want. Decide whether the interval includes the presentation itself, reviewing notes, or making revisions. For a talk with a strict speaking limit, set the timer to the actual allotted duration rather than using a longer practice block as the limit.' },
      { question: 'What if a 45-minute session is too long for my task?', answer: 'Change the focus duration in settings before starting, or choose the 25- or 30-minute timer page. If a session is already running, it keeps its timing when you navigate. Finish or reset that session before beginning a different plan; a shorter useful block is a valid choice.' },
    ],
    related: ['30-minute-timer', '50-minute-timer', 'focus-timer', 'study-timer', 'study-with-friends'],
    finalHeading: 'Make space for a complete attempt',
    finalCopy: 'Choose what you want to produce and give it the next 45 minutes.',
  },
}
