export const seoSlugs = [
  'pomodoro-timer',
  'study-timer',
  'focus-timer',
  'aesthetic-timer',
  'timer-for-studying',
  'online-pomodoro-timer',
  'study-with-me',
  'study-with-friends',
  'pomodoro-with-friends',
  'study-timer-with-friends',
  'online-study-room',
  '25-minute-timer',
  '30-minute-timer',
  '45-minute-timer',
  '50-minute-timer',
  '60-minute-timer',
  '90-minute-timer',
  '25-5-pomodoro',
  '50-10-pomodoro',
  '52-17-rule',
  'pomodoro-for-students',
  'pomodoro-for-developers',
  'pomodoro-for-programmers',
  'pomodoro-for-writers',
  'pomodoro-for-freelancers',
  'pomodoro-for-remote-work',
  'pomodoro-for-adhd',
  'study-timer-for-exams',
  'sat-timer',
  'act-timer',
  'gcse-study-timer',
  'a-level-study-timer',
  'ielts-study-timer',
  'toefl-study-timer',
  'gre-study-timer',
  'mcat-study-timer',
  'jee-study-timer',
  'neet-study-timer',
] as const

export type SeoSlug = typeof seoSlugs[number]

export const seoToolLabels: Record<SeoSlug, string> = {
  'pomodoro-timer': 'Pomodoro Timer',
  'study-timer': 'Study Timer',
  'focus-timer': 'Focus Timer',
  'aesthetic-timer': 'Aesthetic Timer',
  'timer-for-studying': 'Timer for Studying',
  'online-pomodoro-timer': 'Online Pomodoro Timer',
  'study-with-me': 'Study With Me',
  'study-with-friends': 'Study With Friends',
  'pomodoro-with-friends': 'Pomodoro With Friends',
  'study-timer-with-friends': 'Study Timer With Friends',
  'online-study-room': 'Online Study Room',
  '25-minute-timer': '25 Minute Timer',
  '30-minute-timer': '30 Minute Timer',
  '45-minute-timer': '45 Minute Timer',
  '50-minute-timer': '50 Minute Timer',
  '60-minute-timer': '60 Minute Timer',
  '90-minute-timer': '90 Minute Timer',
  '25-5-pomodoro': '25/5 Pomodoro',
  '50-10-pomodoro': '50/10 Pomodoro',
  '52-17-rule': '52/17 Rule',
  'pomodoro-for-students': 'Pomodoro for Students',
  'pomodoro-for-developers': 'Pomodoro for Developers',
  'pomodoro-for-programmers': 'Pomodoro for Programmers',
  'pomodoro-for-writers': 'Pomodoro for Writers',
  'pomodoro-for-freelancers': 'Pomodoro for Freelancers',
  'pomodoro-for-remote-work': 'Pomodoro for Remote Work',
  'pomodoro-for-adhd': 'Pomodoro for ADHD',
  'study-timer-for-exams': 'Study Timer for Exams',
  'sat-timer': 'SAT Timer',
  'act-timer': 'ACT Timer',
  'gcse-study-timer': 'GCSE Study Timer',
  'a-level-study-timer': 'A-Level Study Timer',
  'ielts-study-timer': 'IELTS Study Timer',
  'toefl-study-timer': 'TOEFL Study Timer',
  'gre-study-timer': 'GRE Study Timer',
  'mcat-study-timer': 'MCAT Study Timer',
  'jee-study-timer': 'JEE Study Timer',
  'neet-study-timer': 'NEET Study Timer',
}

export function isSeoPath(pathname: string) {
  return seoSlugs.some((slug) => pathname === `/${slug}` || pathname === `/${slug}/`)
}
